### ISSUE TITLE
mpirun freud meet problem

### ISSUE THREAD

**Issue by zhangyemayapro** [glotzerlab/freud#912]
I'm using freud as a hoomd callback.
When I run the script as
'mpirun -n 2 python3 umbrella_sampling_main.py --mode=cpu'

**Error output**
I got the error
` File "freud/locality.pyx", line 1362, in freud.locality.NearestNeighbors.compute
RuntimeError: Cannot generate a cell list of 0 particles.`

**System configuration (please complete the following information):**
 - ubuntu 20.04
 - Version of Python [e.g. 3.6.9]
 - Version of freud [e.g. 1.2.2]

**Additional context**
thanks for your help.

**Comment by tommy-waltmann** [comment]
Can you attach a script that reproduces the error you are seeing?

Without that, I can only guess as to what may be the issue. My guess right now is that the MPI domain decomposition in hoomd is creating an MPI rank which has 0 particles, causing freud to fail because of a null input. Please double check that this is not the issue.

**Comment by bdice** [comment]
As @tommy-waltmann suggested, you probably need to use freud on the whole system, not on a local domain decomposition from one MPI rank. The freud library is designed for periodic boxes, not decomposed systems, and it may not handle HOOMD’s use of ghost particles correctly.

**Comment by zhangyemayapro** [comment]
```
#I'm using freud as a callback to run umbrella sampling
#this is a function used to calculate orderparameter
class OrderParameterAveQlNear(OrderParameter):
    def __init__(self, box, rcut, l, kn):
        print("HelloFromAveQlNear")
        self.sl = shop.LocalQlNear(box, rcut, l, kn)
        print("DoneInitializingOP")
    def getOrder(self, xyz, quat=''):
        self.sl.computeAve(xyz)
        return np.mean(np.ma.masked_array(np.real(self.sl.ave_Ql),np.isnan(np.real(self.sl.ave_Ql))))
    def resetBox(self, newbox):
        self.sl.setBox(newbox)

#self.system is a HOOMD system
self.snapshot = self.system.take_snapshot(particles=True);
self.pos = self.snapshot.particles.position

self.orderparameter=OrderParameterAveQlNear()
self.order = self.orderparameter.getOrder(xyz=self.pos,quat=self.quat)
```
The error come with
`self.sl.computeAve(xyz)`
`xyz` is particle position
I think you are right, that the MPI domain decomposition in hoomd is creating an MPI rank which has 0 particles.
How can I use freud on the whole system?
Thanks for your help~

**Comment by bdice** [comment]
It looks like you are using classes from an old version of freud (LocalQlNear). There have been a number of crucial bugs fixed in Steinhardt order parameters since then — it is very possible that calculations may not be correct in the version you are using. The freud library now has rigorous testing and validation for Steinhardt calculations. I would strongly encourage you to update to the current version of freud. Additionally, we cannot provide good support for versions that old (it is likely that no current freud developers have used that old version).

As far as systems go, you probably want to use a HOOMD snapshot of the whole system and pass that snapshot object as the “system” parameter of a class’s “compute” method (this assumes the use of the current freud API).

This example may point you in the right direction: https://freud.readthedocs.io/en/latest/gettingstarted/examples/examples/HOOMD-MC-W6/HOOMD-MC-W6.html

If you need help installing a newer version of freud, please see the installation instructions here: https://freud.readthedocs.io/en/latest/gettingstarted/installation.html

**Comment by zhangyemayapro** [comment]
thanks for your help. I'll try it

**Comment by joaander** [comment]
Are the two MPI ranks two independent simulations in the umbrella sampling run (partitions)? Or are the 2 MPI ranks both used for the same simulation with domain decomposition?

**Comment by zhangyemayapro** [comment]
I have update to the latest version of freud(2.8.0), 
and run the script given in
[https://freud.readthedocs.io/en/latest/gettingstarted/examples/examples/HOOMD-MC-W6/HOOMD-MC-W6.html]

`mpirun -n 8 python3 test_pi.py --mode=cpu`
While I still get the same error
```
  File "locality.pyx", line 812, in freud.locality._RawPoints.__cinit__
ValueError: Cannot create a NeighborQuery with 0 particles.
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 1 in communicator MPI_COMM_WORLD
with errorcode 16.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[Mercury:120556] 6 more processes have sent help message help-mpi-api.txt / mpi-abort
[Mercury:120556] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

```
I think the problem may come from  hoomd itself
That is: only some mpi rank can get the right snapshot.
Thanks for your help.

**Comment by zhangyemayapro** [comment]
> Are the two MPI ranks two independent simulations in the umbrella sampling run (partitions)? Or are the 2 MPI ranks both used for the same simulation with domain decomposition?

I'm not sure

**Comment by tommy-waltmann** [comment]
If you post a minimal script which reproduces your problem, we can help you fix it.

**Comment by zhangyemayapro** [comment]
Thanks I run the following script:
```
import freud
import hoomd
import matplotlib.pyplot as plt
import numpy as np
from hoomd import hpmc
hoomd.context.initialize("")
system = hoomd.init.create_lattice(hoomd.lattice.sc(a=1), n=10)
mc = hpmc.integrate.sphere(seed=42, d=0.1, a=0.1)
mc.shape_param.set("A", diameter=0.5)
w6 = freud.order.Steinhardt(l=6, wl=True)

def calc_W6(timestep):
    hoomd.util.quiet_status()
    snap = system.take_snapshot()
    hoomd.util.unquiet_status()
    w6.compute(system=snap, neighbors={"num_neighbors": 12})
    return np.mean(w6.particle_order)

logger = hoomd.analyze.log(
    filename="output.log",
    quantities=["w6"],
    period=100,
    header_prefix="#",
    overwrite=True,
)

logger.register_callback("w6", calc_W6)

hoomd.run(1e4)
```

With command:
`mpirun -n 8 python3 testmpi.py --mode=cpu`

The error:
```
 File "testmpi.py", line 31, in <module>
    hoomd.run(1e4)
  File "/home/yzhang/miniconda3/envs/hdfr4/lib/python3.8/site-packages/hoomd/__init__.py", line 201, in run
    context.current.system.run(int(tsteps), callback_period, callback, limit_hours, int(limit_multiple));
  File "testmpi.py", line 17, in calc_W6
    w6.compute(system=snap, neighbors={"num_neighbors": 12})
  File "util.pyx", line 165, in freud.util._Compute.__getattribute__.compute_wrapper
  File "order.pyx", line 727, in freud.order.Steinhardt.compute
  File "locality.pyx", line 925, in freud.locality._PairCompute._preprocess_arguments
  File "locality.pyx", line 371, in freud.locality.NeighborQuery.from_system
  File "locality.pyx", line 812, in freud.locality._RawPoints.__cinit__
ValueError: Cannot create a NeighborQuery with 0 particles.
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 2 in communicator MPI_COMM_WORLD
with errorcode 16.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[Mercury:125216] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2198
[Mercury:125216] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2198
[Mercury:125216] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2198
[Mercury:125216] 6 more processes have sent help message help-mpi-api.txt / mpi-abort
[Mercury:125216] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

Thanks~

**Comment by joaander** [comment]
`take_snapshot` gives the particle positions only on rank 0. You need to wrap the `w6.compute` call inside a check that the current rank is 0. Return 0 in the else condition - the GSD writer will only use the return value from the root rank.

For more details, see https://hoomd-blue.readthedocs.io/en/latest/tutorial/03-Parallel-Simulations-With-MPI/00-index.html . The tutorial is for the v3 API, but the concepts are the same for both v2 and v3.

**Comment by zhangyemayapro** [comment]
thank

> `take_snapshot` gives the particle positions only on rank 0. You need to wrap the `w6.compute` call inside a check that the current rank is 0. Return 0 in the else condition - the GSD writer will only use the return value from the root rank.
> 
> For more details, see https://hoomd-blue.readthedocs.io/en/latest/tutorial/03-Parallel-Simulations-With-MPI/00-index.html . The tutorial is for the v3 API, but the concepts are the same for both v2 and v3.

thanks for your help~

**Comment by zhangyemayapro** [comment]
Thanks for your help, I've solved the problem~
